name: release
on:
  workflow_run:
    workflows: [test]
    branches: [main]
    types: [completed]

env:
  PACKAGE_NAME: github.com/nisimpson/piper

jobs:
  on-success:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
      - name: Semver bump
        id: semver
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.semver.outputs.new_tag }}
          name: Release ${{ steps.semver.outputs.new_tag }}
          body: ${{ steps.semver.outputs.changelog }}
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish Module
        run: GOPROXY=proxy.golang.org go list -m ${{ env.PACKAGE_NAME }}@${{ steps.semver.outputs.new_tag}}

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
